=== lazydog-org/enhanced-jndi-realm/src/main/resources/META-INF/xsd/role-to-groups.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns="http://lazydog.org/xml/ns/role-to-groups"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://lazydog.org/xml/ns/role-to-groups"
    elementFormDefault="qualified">

    <xs:element name="role-to-groups-mapping">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="role-name" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>

                            The role name for the mapping.

                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="group-dn" maxOccurs="unbounded" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>

                            A group distinguished name for the mapping.

                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="role-to-groups-mappings">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="role-to-groups-mapping" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>

                            A role to groups mapping.

                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== lazydog-org/enhanced-jndi-realm/src/test/resources/META-INF/role-to-groups.xml
<?xml version="1.0" encoding="UTF-8"?>
<role-to-groups-mappings
    xmlns="http://lazydog.org/xml/ns/role-to-groups"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://lazydog.org/xml/ns/role-to-groups
                        http://lazydog.org/xml/ns/role-to-groups/role-to-groups.xsd">

    <role-to-groups-mapping>
        <role-name>role1</role-name>
        <group-dn>cn=group1,ou=groups,dc=lazydog,dc=org</group-dn>
        <group-dn>cn=group2,ou=groups,dc=lazydog,dc=org</group-dn>
    </role-to-groups-mapping>
    <role-to-groups-mapping>
        <role-name>role2</role-name>
        <group-dn>cn=group3,ou=groups,dc=lazydog,dc=org</group-dn>
        <group-dn>cn=group4,ou=groups,dc=lazydog,dc=org</group-dn>
    </role-to-groups-mapping>
</role-to-groups-mappings>
